// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaKw2G8QmD3H-Zk3s_c1ixnewKVRD7TDo',
    appId: '1:492352961365:web:32ff7f7298134a03c54ddc',
    messagingSenderId: '492352961365',
    projectId: 'ment-o-help-72f49',
    authDomain: 'ment-o-help-72f49.firebaseapp.com',
    storageBucket: 'ment-o-help-72f49.appspot.com',
    measurementId: 'G-JY0FYC72KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ItMi-G6oFty3OqyX0lOrIZr6hNkApew',
    appId: '1:492352961365:android:f66ebf93e759d5dcc54ddc',
    messagingSenderId: '492352961365',
    projectId: 'ment-o-help-72f49',
    storageBucket: 'ment-o-help-72f49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVAm2Faq5f7L2ICHDced1mOBywE9zbbjM',
    appId: '1:492352961365:ios:46bd69add52f5f2bc54ddc',
    messagingSenderId: '492352961365',
    projectId: 'ment-o-help-72f49',
    storageBucket: 'ment-o-help-72f49.appspot.com',
    iosBundleId: 'com.example.mentOHelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVAm2Faq5f7L2ICHDced1mOBywE9zbbjM',
    appId: '1:492352961365:ios:e112a093827ed1afc54ddc',
    messagingSenderId: '492352961365',
    projectId: 'ment-o-help-72f49',
    storageBucket: 'ment-o-help-72f49.appspot.com',
    iosBundleId: 'com.example.mentOHelp.RunnerTests',
  );
}
